In [1]:
import numpy as np

In [3]:
np.power(2,6)

64

In [6]:
a=[2,3,4,5,6]
np.power(a,2)

array([ 4,  9, 16, 25, 36], dtype=int32)

In [5]:
np.sqrt(16)

4.0

In [11]:
print("BLACKHOLES ARE MYSTERIOUS")

BLACKHOLES ARE MYSTERIOUS


In [14]:
print("HELLO EVERYONE!!!\nWELCOME TO IST...\nHOPEFULLY YOU'LL LEARN TO MANAGE DEPRESSION HERE")

HELLO EVERYONE!!!
WELCOME TO IST...
HOPEFULLY YOU'LL LEARN TO MANAGE DEPRESSION HERE


In [15]:
a=[1,2,3,4,5,6,7,8,9]
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
angle=[0,38,43,51,65,78,84]
np.sin(angle)

array([ 0.        ,  0.29636858, -0.83177474,  0.67022918,  0.82682868,
        0.51397846,  0.73319032])